### PR TITLE
candidate to fix #245 by ensuring dc config for tenant is always used

### LINKED ISSUE #245: Establish why DataCite prefixes were mixed up across tenants
BL and BL-demo were minting DOIs with the Kew Gardens prefix. This resulted in errors 403 (credentials incorrect) and 500 (internal server error). 

Correct credentials/prefixes were shown in the superadmin but were minting incorrectly with the 10.34885 prefix. On re-saving the credentials, bug seems to be fixed, but we would like to understand how this happened and how it can be avoided in future. Is this related to the migration as these are the first DOIs we have produced since the change freeze was lifted

### PR DESCRIPTION
**Pull request by cziaarm**
Fixes #245 ; 

Present tense short summary (50 characters or less)

When DataCiteRegistrar created a DataCiteClient it used class attributes that could be cached between two Registration events even if those two events were instigated by two different tenants. This change fetches the DC config from the current tenant's data_cite_endpoint before creating the DataCiteClient.

### CODE REVIEW

File: config/initializers/hyrax-doi.rb [hunk 1]
```diff
@@ -168,3 +168,18 @@ def assign_for(object:, attribute: :identifier)
...
+
+# Forces DataCiteRegistrar to initializew a new client everytime. 
+# A fix for #245 https://github.com/scientist-softserv/britishlibrary/issues/245
+# Prevents leaching of datacite config between tenants when minting DOIs by ensuring
+# that the datacite credentials always come from the account that kicked the job off
+Hyrax::DOI::DataCiteRegistrar.class_eval do
+
+  def client 
+    current_tenant = Apartment::Tenant.current
+    @datacite_endpoint ||= Account.find_by(tenant: current_tenant).data_cite_endpoint
```
Comment (jeremyf) [inline config/initializers/hyrax-doi.rb:180]: I'm wondering if the prefix causes problems as well?  https://github.com/samvera-labs/hyrax-doi/blob/main/app/services/hyrax/doi/datacite_registrar.rb#L10-L12

Also, I think we may want to consider memoize the entire client:

```ruby
def client
  @client ||= begin
    current_tenant = Apartment::Tenant.current
    datacite_endpoint = Account.find_by(tenant: current_tenant).data_cite_endpoint
    Hyrax::DOI::DataCiteClient.new(username: datacite_endpoint.username, password: datacite_endpoint.password, prefix: datacite_endpoint.prefix, mode: datacite_endpoint.mode)
  end
end
```

Also a `class_attribute` can be set in the instance (recommended during an initialize).  So we could do `self.password = <client's data cite end point password>`.

Comment (cziaarm) [reply config/initializers/hyrax-doi.rb:180]: All excellent points! The prefix in the initialize wasn't causing observable issues for me, but could well do in some contexts. Let me see if I can knock this in to a better shape...

File: config/initializers/hyrax-doi.rb [hunk 2]
```diff
@@ -168,3 +168,25 @@ def assign_for(object:, attribute: :identifier)
...
   end
 end
+
+# Forces DataCiteRegistrar to initializew a new client everytime. 
+# A fix for #245 https://github.com/scientist-softserv/britishlibrary/issues/245
+# Prevents leaching of datacite config between tenants when minting DOIs by ensuring
+# that the datacite credentials always come from the account that kicked the job off
+Hyrax::DOI::DataCiteRegistrar.class_eval do
+
+  def initialize(builder: Hyrax::Identifier::Builder.new(prefix: self.prefix))
```
Comment (jeremyf) [inline config/initializers/hyrax-doi.rb:178]: One foible with this is that the `self.prefix` at this point of evaluation is the class's assigned prefix (which is set during the request.  It is not the data `datacite_endpoint.prefix`.

I suspect we would want to do the following:

```ruby
def initialize(builder: nil)
...
super(builder: Hyrax::Identifier::Builder.new(prefix: self.prefix))
```

**Review by jeremyf — APPROVED** [review]
